export const LAYOUT = {
  WINDOW_HEIGHT: 340,
  CONTROL_BAR_HEIGHT: 64,
  CARD_WIDTH: 210,
  CARD_GAP: 24,
  SIDE_PADDING: 20,
  CARD_VERTICAL_PADDING: 20,
};

export const CLIP_LIST_HEIGHT = LAYOUT.WINDOW_HEIGHT - LAYOUT.CONTROL_BAR_HEIGHT;
export const TOTAL_COLUMN_WIDTH = LAYOUT.CARD_WIDTH + LAYOUT.CARD_GAP;
